### ISSUE TITLE
imbibe fails on journals that don't specify a short title

### ISSUE THREAD

**Issue by dominicelse** [dominicelse/imbibe#1]
```
$ imbibe --eprint 1603.03923
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dom/git/autobib/imbibe/__main__.py", line 288, in <module>
    populate_doi_information(bibitems)
  File "/home/dom/git/autobib/imbibe/__main__.py", line 53, in populate_doi_information
    bibitem.read_journal_information(result)
  File "/home/dom/git/autobib/imbibe/__main__.py", line 239, in read_journal_information
    self.journal_short = cr_result['short-container-title'][0]
IndexError: list index out of range
```

**Comment by dominicelse** [comment]
Fixed, although note that the particular paper used as an example here still fails, because the CrossRef record is missing any page number information.
